version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/workspace/healthlink-deploy
    overwrite: yes
permissions:
  - object: /home/ubuntu/workspace/healthlink-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: /home/ubuntu/workspace/auto_deploy.sh
      timeout: 60
      runas: ubuntu
