# docker-compose.yml
version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: