// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nursing_api/ent/predicate"
	"nursing_api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUserEmail sets the "user_email" field.
func (uu *UserUpdate) SetUserEmail(s string) *UserUpdate {
	uu.mutation.SetUserEmail(s)
	return uu
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUserEmail(s *string) *UserUpdate {
	if s != nil {
		uu.SetUserEmail(*s)
	}
	return uu
}

// SetUserPassword sets the "user_password" field.
func (uu *UserUpdate) SetUserPassword(s string) *UserUpdate {
	uu.mutation.SetUserPassword(s)
	return uu
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUserPassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetUserPassword(*s)
	}
	return uu
}

// SetUserStatus sets the "user_status" field.
func (uu *UserUpdate) SetUserStatus(s string) *UserUpdate {
	uu.mutation.SetUserStatus(s)
	return uu
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUserStatus(s *string) *UserUpdate {
	if s != nil {
		uu.SetUserStatus(*s)
	}
	return uu
}

// SetUserType sets the "user_type" field.
func (uu *UserUpdate) SetUserType(s string) *UserUpdate {
	uu.mutation.SetUserType(s)
	return uu
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUserType(s *string) *UserUpdate {
	if s != nil {
		uu.SetUserType(*s)
	}
	return uu
}

// SetFailCount sets the "fail_count" field.
func (uu *UserUpdate) SetFailCount(i int) *UserUpdate {
	uu.mutation.ResetFailCount()
	uu.mutation.SetFailCount(i)
	return uu
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (uu *UserUpdate) SetNillableFailCount(i *int) *UserUpdate {
	if i != nil {
		uu.SetFailCount(*i)
	}
	return uu
}

// AddFailCount adds i to the "fail_count" field.
func (uu *UserUpdate) AddFailCount(i int) *UserUpdate {
	uu.mutation.AddFailCount(i)
	return uu
}

// SetLastSignedIn sets the "last_signed_in" field.
func (uu *UserUpdate) SetLastSignedIn(t time.Time) *UserUpdate {
	uu.mutation.SetLastSignedIn(t)
	return uu
}

// SetNillableLastSignedIn sets the "last_signed_in" field if the given value is not nil.
func (uu *UserUpdate) SetNillableLastSignedIn(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetLastSignedIn(*t)
	}
	return uu
}

// ClearLastSignedIn clears the value of the "last_signed_in" field.
func (uu *UserUpdate) ClearLastSignedIn() *UserUpdate {
	uu.mutation.ClearLastSignedIn()
	return uu
}

// SetCreatedAt sets the "created_at" field.
func (uu *UserUpdate) SetCreatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetCreatedAt(t)
	return uu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableCreatedAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetCreatedAt(*t)
	}
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUpdatedAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetUpdatedAt(*t)
	}
	return uu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (uu *UserUpdate) ClearUpdatedAt() *UserUpdate {
	uu.mutation.ClearUpdatedAt()
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UserEmail(); ok {
		_spec.SetField(user.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := uu.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.UserStatus(); ok {
		_spec.SetField(user.FieldUserStatus, field.TypeString, value)
	}
	if value, ok := uu.mutation.UserType(); ok {
		_spec.SetField(user.FieldUserType, field.TypeString, value)
	}
	if value, ok := uu.mutation.FailCount(); ok {
		_spec.SetField(user.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedFailCount(); ok {
		_spec.AddField(user.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := uu.mutation.LastSignedIn(); ok {
		_spec.SetField(user.FieldLastSignedIn, field.TypeTime, value)
	}
	if uu.mutation.LastSignedInCleared() {
		_spec.ClearField(user.FieldLastSignedIn, field.TypeTime)
	}
	if value, ok := uu.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if uu.mutation.UpdatedAtCleared() {
		_spec.ClearField(user.FieldUpdatedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUserEmail sets the "user_email" field.
func (uuo *UserUpdateOne) SetUserEmail(s string) *UserUpdateOne {
	uuo.mutation.SetUserEmail(s)
	return uuo
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserEmail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUserEmail(*s)
	}
	return uuo
}

// SetUserPassword sets the "user_password" field.
func (uuo *UserUpdateOne) SetUserPassword(s string) *UserUpdateOne {
	uuo.mutation.SetUserPassword(s)
	return uuo
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserPassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUserPassword(*s)
	}
	return uuo
}

// SetUserStatus sets the "user_status" field.
func (uuo *UserUpdateOne) SetUserStatus(s string) *UserUpdateOne {
	uuo.mutation.SetUserStatus(s)
	return uuo
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserStatus(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUserStatus(*s)
	}
	return uuo
}

// SetUserType sets the "user_type" field.
func (uuo *UserUpdateOne) SetUserType(s string) *UserUpdateOne {
	uuo.mutation.SetUserType(s)
	return uuo
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserType(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUserType(*s)
	}
	return uuo
}

// SetFailCount sets the "fail_count" field.
func (uuo *UserUpdateOne) SetFailCount(i int) *UserUpdateOne {
	uuo.mutation.ResetFailCount()
	uuo.mutation.SetFailCount(i)
	return uuo
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableFailCount(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetFailCount(*i)
	}
	return uuo
}

// AddFailCount adds i to the "fail_count" field.
func (uuo *UserUpdateOne) AddFailCount(i int) *UserUpdateOne {
	uuo.mutation.AddFailCount(i)
	return uuo
}

// SetLastSignedIn sets the "last_signed_in" field.
func (uuo *UserUpdateOne) SetLastSignedIn(t time.Time) *UserUpdateOne {
	uuo.mutation.SetLastSignedIn(t)
	return uuo
}

// SetNillableLastSignedIn sets the "last_signed_in" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableLastSignedIn(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetLastSignedIn(*t)
	}
	return uuo
}

// ClearLastSignedIn clears the value of the "last_signed_in" field.
func (uuo *UserUpdateOne) ClearLastSignedIn() *UserUpdateOne {
	uuo.mutation.ClearLastSignedIn()
	return uuo
}

// SetCreatedAt sets the "created_at" field.
func (uuo *UserUpdateOne) SetCreatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetCreatedAt(t)
	return uuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableCreatedAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetCreatedAt(*t)
	}
	return uuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetUpdatedAt(*t)
	}
	return uuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (uuo *UserUpdateOne) ClearUpdatedAt() *UserUpdateOne {
	uuo.mutation.ClearUpdatedAt()
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UserEmail(); ok {
		_spec.SetField(user.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.UserStatus(); ok {
		_spec.SetField(user.FieldUserStatus, field.TypeString, value)
	}
	if value, ok := uuo.mutation.UserType(); ok {
		_spec.SetField(user.FieldUserType, field.TypeString, value)
	}
	if value, ok := uuo.mutation.FailCount(); ok {
		_spec.SetField(user.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedFailCount(); ok {
		_spec.AddField(user.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.LastSignedIn(); ok {
		_spec.SetField(user.FieldLastSignedIn, field.TypeTime, value)
	}
	if uuo.mutation.LastSignedInCleared() {
		_spec.ClearField(user.FieldLastSignedIn, field.TypeTime)
	}
	if value, ok := uuo.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if uuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(user.FieldUpdatedAt, field.TypeTime)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
