// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"nursing_api/pkg/ent/predicate"
	"nursing_api/pkg/ent/prescription"
	"nursing_api/pkg/ent/prescriptionitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrescriptionQuery is the builder for querying Prescription entities.
type PrescriptionQuery struct {
	config
	ctx                   *QueryContext
	order                 []prescription.OrderOption
	inters                []Interceptor
	predicates            []predicate.Prescription
	withPrescriptionItems *PrescriptionItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrescriptionQuery builder.
func (pq *PrescriptionQuery) Where(ps ...predicate.Prescription) *PrescriptionQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PrescriptionQuery) Limit(limit int) *PrescriptionQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PrescriptionQuery) Offset(offset int) *PrescriptionQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PrescriptionQuery) Unique(unique bool) *PrescriptionQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PrescriptionQuery) Order(o ...prescription.OrderOption) *PrescriptionQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryPrescriptionItems chains the current query on the "prescription_items" edge.
func (pq *PrescriptionQuery) QueryPrescriptionItems() *PrescriptionItemQuery {
	query := (&PrescriptionItemClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prescription.Table, prescription.FieldID, selector),
			sqlgraph.To(prescriptionitem.Table, prescriptionitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, prescription.PrescriptionItemsTable, prescription.PrescriptionItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Prescription entity from the query.
// Returns a *NotFoundError when no Prescription was found.
func (pq *PrescriptionQuery) First(ctx context.Context) (*Prescription, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prescription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PrescriptionQuery) FirstX(ctx context.Context) *Prescription {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Prescription ID from the query.
// Returns a *NotFoundError when no Prescription ID was found.
func (pq *PrescriptionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prescription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PrescriptionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Prescription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Prescription entity is found.
// Returns a *NotFoundError when no Prescription entities are found.
func (pq *PrescriptionQuery) Only(ctx context.Context) (*Prescription, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prescription.Label}
	default:
		return nil, &NotSingularError{prescription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PrescriptionQuery) OnlyX(ctx context.Context) *Prescription {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Prescription ID in the query.
// Returns a *NotSingularError when more than one Prescription ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PrescriptionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prescription.Label}
	default:
		err = &NotSingularError{prescription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PrescriptionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Prescriptions.
func (pq *PrescriptionQuery) All(ctx context.Context) ([]*Prescription, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Prescription, *PrescriptionQuery]()
	return withInterceptors[[]*Prescription](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PrescriptionQuery) AllX(ctx context.Context) []*Prescription {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Prescription IDs.
func (pq *PrescriptionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(prescription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PrescriptionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PrescriptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PrescriptionQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PrescriptionQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PrescriptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PrescriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrescriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PrescriptionQuery) Clone() *PrescriptionQuery {
	if pq == nil {
		return nil
	}
	return &PrescriptionQuery{
		config:                pq.config,
		ctx:                   pq.ctx.Clone(),
		order:                 append([]prescription.OrderOption{}, pq.order...),
		inters:                append([]Interceptor{}, pq.inters...),
		predicates:            append([]predicate.Prescription{}, pq.predicates...),
		withPrescriptionItems: pq.withPrescriptionItems.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithPrescriptionItems tells the query-builder to eager-load the nodes that are connected to
// the "prescription_items" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PrescriptionQuery) WithPrescriptionItems(opts ...func(*PrescriptionItemQuery)) *PrescriptionQuery {
	query := (&PrescriptionItemClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withPrescriptionItems = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Prescription.Query().
//		GroupBy(prescription.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PrescriptionQuery) GroupBy(field string, fields ...string) *PrescriptionGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrescriptionGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = prescription.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.Prescription.Query().
//		Select(prescription.FieldUserID).
//		Scan(ctx, &v)
func (pq *PrescriptionQuery) Select(fields ...string) *PrescriptionSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PrescriptionSelect{PrescriptionQuery: pq}
	sbuild.label = prescription.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrescriptionSelect configured with the given aggregations.
func (pq *PrescriptionQuery) Aggregate(fns ...AggregateFunc) *PrescriptionSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PrescriptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !prescription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PrescriptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Prescription, error) {
	var (
		nodes       = []*Prescription{}
		_spec       = pq.querySpec()
		loadedTypes = [1]bool{
			pq.withPrescriptionItems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Prescription).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Prescription{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withPrescriptionItems; query != nil {
		if err := pq.loadPrescriptionItems(ctx, query, nodes,
			func(n *Prescription) { n.Edges.PrescriptionItems = []*PrescriptionItem{} },
			func(n *Prescription, e *PrescriptionItem) {
				n.Edges.PrescriptionItems = append(n.Edges.PrescriptionItems, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PrescriptionQuery) loadPrescriptionItems(ctx context.Context, query *PrescriptionItemQuery, nodes []*Prescription, init func(*Prescription), assign func(*Prescription, *PrescriptionItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Prescription)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(prescriptionitem.FieldPrescriptionID)
	}
	query.Where(predicate.PrescriptionItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(prescription.PrescriptionItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrescriptionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "prescription_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *PrescriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PrescriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(prescription.Table, prescription.Columns, sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prescription.FieldID)
		for i := range fields {
			if fields[i] != prescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PrescriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(prescription.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = prescription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrescriptionGroupBy is the group-by builder for Prescription entities.
type PrescriptionGroupBy struct {
	selector
	build *PrescriptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PrescriptionGroupBy) Aggregate(fns ...AggregateFunc) *PrescriptionGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PrescriptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrescriptionQuery, *PrescriptionGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PrescriptionGroupBy) sqlScan(ctx context.Context, root *PrescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrescriptionSelect is the builder for selecting fields of Prescription entities.
type PrescriptionSelect struct {
	*PrescriptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PrescriptionSelect) Aggregate(fns ...AggregateFunc) *PrescriptionSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PrescriptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrescriptionQuery, *PrescriptionSelect](ctx, ps.PrescriptionQuery, ps, ps.inters, v)
}

func (ps *PrescriptionSelect) sqlScan(ctx context.Context, root *PrescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
