// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nursing_api/pkg/ent/prescription"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrescriptionCreate is the builder for creating a Prescription entity.
type PrescriptionCreate struct {
	config
	mutation *PrescriptionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (pc *PrescriptionCreate) SetUserID(u uuid.UUID) *PrescriptionCreate {
	pc.mutation.SetUserID(u)
	return pc
}

// SetPrescriptionName sets the "prescription_name" field.
func (pc *PrescriptionCreate) SetPrescriptionName(s string) *PrescriptionCreate {
	pc.mutation.SetPrescriptionName(s)
	return pc
}

// SetNillablePrescriptionName sets the "prescription_name" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillablePrescriptionName(s *string) *PrescriptionCreate {
	if s != nil {
		pc.SetPrescriptionName(*s)
	}
	return pc
}

// SetHospitalName sets the "hospital_name" field.
func (pc *PrescriptionCreate) SetHospitalName(s string) *PrescriptionCreate {
	pc.mutation.SetHospitalName(s)
	return pc
}

// SetNillableHospitalName sets the "hospital_name" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableHospitalName(s *string) *PrescriptionCreate {
	if s != nil {
		pc.SetHospitalName(*s)
	}
	return pc
}

// SetTakeDays sets the "take_days" field.
func (pc *PrescriptionCreate) SetTakeDays(i int) *PrescriptionCreate {
	pc.mutation.SetTakeDays(i)
	return pc
}

// SetNillableTakeDays sets the "take_days" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableTakeDays(i *int) *PrescriptionCreate {
	if i != nil {
		pc.SetTakeDays(*i)
	}
	return pc
}

// SetStartedAt sets the "started_at" field.
func (pc *PrescriptionCreate) SetStartedAt(t time.Time) *PrescriptionCreate {
	pc.mutation.SetStartedAt(t)
	return pc
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableStartedAt(t *time.Time) *PrescriptionCreate {
	if t != nil {
		pc.SetStartedAt(*t)
	}
	return pc
}

// SetFinishedAt sets the "finished_at" field.
func (pc *PrescriptionCreate) SetFinishedAt(t time.Time) *PrescriptionCreate {
	pc.mutation.SetFinishedAt(t)
	return pc
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableFinishedAt(t *time.Time) *PrescriptionCreate {
	if t != nil {
		pc.SetFinishedAt(*t)
	}
	return pc
}

// SetMemo sets the "memo" field.
func (pc *PrescriptionCreate) SetMemo(s string) *PrescriptionCreate {
	pc.mutation.SetMemo(s)
	return pc
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableMemo(s *string) *PrescriptionCreate {
	if s != nil {
		pc.SetMemo(*s)
	}
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PrescriptionCreate) SetCreatedAt(t time.Time) *PrescriptionCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableCreatedAt(t *time.Time) *PrescriptionCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PrescriptionCreate) SetUpdatedAt(t time.Time) *PrescriptionCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableUpdatedAt(t *time.Time) *PrescriptionCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PrescriptionCreate) SetID(u uuid.UUID) *PrescriptionCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableID(u *uuid.UUID) *PrescriptionCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// Mutation returns the PrescriptionMutation object of the builder.
func (pc *PrescriptionCreate) Mutation() *PrescriptionMutation {
	return pc.mutation
}

// Save creates the Prescription in the database.
func (pc *PrescriptionCreate) Save(ctx context.Context) (*Prescription, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PrescriptionCreate) SaveX(ctx context.Context) *Prescription {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PrescriptionCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PrescriptionCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PrescriptionCreate) defaults() {
	if _, ok := pc.mutation.TakeDays(); !ok {
		v := prescription.DefaultTakeDays
		pc.mutation.SetTakeDays(v)
	}
	if _, ok := pc.mutation.StartedAt(); !ok {
		v := prescription.DefaultStartedAt()
		pc.mutation.SetStartedAt(v)
	}
	if _, ok := pc.mutation.FinishedAt(); !ok {
		v := prescription.DefaultFinishedAt()
		pc.mutation.SetFinishedAt(v)
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := prescription.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := prescription.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PrescriptionCreate) check() error {
	if _, ok := pc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Prescription.user_id"`)}
	}
	if _, ok := pc.mutation.TakeDays(); !ok {
		return &ValidationError{Name: "take_days", err: errors.New(`ent: missing required field "Prescription.take_days"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Prescription.created_at"`)}
	}
	return nil
}

func (pc *PrescriptionCreate) sqlSave(ctx context.Context) (*Prescription, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PrescriptionCreate) createSpec() (*Prescription, *sqlgraph.CreateSpec) {
	var (
		_node = &Prescription{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(prescription.Table, sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.UserID(); ok {
		_spec.SetField(prescription.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := pc.mutation.PrescriptionName(); ok {
		_spec.SetField(prescription.FieldPrescriptionName, field.TypeString, value)
		_node.PrescriptionName = value
	}
	if value, ok := pc.mutation.HospitalName(); ok {
		_spec.SetField(prescription.FieldHospitalName, field.TypeString, value)
		_node.HospitalName = value
	}
	if value, ok := pc.mutation.TakeDays(); ok {
		_spec.SetField(prescription.FieldTakeDays, field.TypeInt, value)
		_node.TakeDays = value
	}
	if value, ok := pc.mutation.StartedAt(); ok {
		_spec.SetField(prescription.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := pc.mutation.FinishedAt(); ok {
		_spec.SetField(prescription.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := pc.mutation.Memo(); ok {
		_spec.SetField(prescription.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(prescription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(prescription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PrescriptionCreateBulk is the builder for creating many Prescription entities in bulk.
type PrescriptionCreateBulk struct {
	config
	err      error
	builders []*PrescriptionCreate
}

// Save creates the Prescription entities in the database.
func (pcb *PrescriptionCreateBulk) Save(ctx context.Context) ([]*Prescription, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Prescription, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrescriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PrescriptionCreateBulk) SaveX(ctx context.Context) []*Prescription {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PrescriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PrescriptionCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
