// Code generated by ent, DO NOT EDIT.

package ent

import (
	"nursing_api/pkg/ent/medicine"
	"nursing_api/pkg/ent/prescription"
	"nursing_api/pkg/ent/prescriptionitem"
	"nursing_api/pkg/ent/schema"
	"nursing_api/pkg/ent/takehistoryitem"
	"nursing_api/pkg/ent/takehistorymemo"
	"nursing_api/pkg/ent/timezone"
	"nursing_api/pkg/ent/token"
	"nursing_api/pkg/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	medicineFields := schema.Medicine{}.Fields()
	_ = medicineFields
	// medicineDescCreatedAt is the schema descriptor for created_at field.
	medicineDescCreatedAt := medicineFields[19].Descriptor()
	// medicine.DefaultCreatedAt holds the default value on creation for the created_at field.
	medicine.DefaultCreatedAt = medicineDescCreatedAt.Default.(func() time.Time)
	// medicineDescID is the schema descriptor for id field.
	medicineDescID := medicineFields[0].Descriptor()
	// medicine.DefaultID holds the default value on creation for the id field.
	medicine.DefaultID = medicineDescID.Default.(func() uuid.UUID)
	prescriptionFields := schema.Prescription{}.Fields()
	_ = prescriptionFields
	// prescriptionDescTakeDays is the schema descriptor for take_days field.
	prescriptionDescTakeDays := prescriptionFields[4].Descriptor()
	// prescription.DefaultTakeDays holds the default value on creation for the take_days field.
	prescription.DefaultTakeDays = prescriptionDescTakeDays.Default.(int)
	// prescriptionDescStartedAt is the schema descriptor for started_at field.
	prescriptionDescStartedAt := prescriptionFields[5].Descriptor()
	// prescription.DefaultStartedAt holds the default value on creation for the started_at field.
	prescription.DefaultStartedAt = prescriptionDescStartedAt.Default.(func() time.Time)
	// prescriptionDescFinishedAt is the schema descriptor for finished_at field.
	prescriptionDescFinishedAt := prescriptionFields[6].Descriptor()
	// prescription.DefaultFinishedAt holds the default value on creation for the finished_at field.
	prescription.DefaultFinishedAt = prescriptionDescFinishedAt.Default.(func() time.Time)
	// prescriptionDescCreatedAt is the schema descriptor for created_at field.
	prescriptionDescCreatedAt := prescriptionFields[7].Descriptor()
	// prescription.DefaultCreatedAt holds the default value on creation for the created_at field.
	prescription.DefaultCreatedAt = prescriptionDescCreatedAt.Default.(func() time.Time)
	// prescriptionDescID is the schema descriptor for id field.
	prescriptionDescID := prescriptionFields[0].Descriptor()
	// prescription.DefaultID holds the default value on creation for the id field.
	prescription.DefaultID = prescriptionDescID.Default.(func() uuid.UUID)
	prescriptionitemFields := schema.PrescriptionItem{}.Fields()
	_ = prescriptionitemFields
	// prescriptionitemDescTotalAmount is the schema descriptor for total_amount field.
	prescriptionitemDescTotalAmount := prescriptionitemFields[9].Descriptor()
	// prescriptionitem.DefaultTotalAmount holds the default value on creation for the total_amount field.
	prescriptionitem.DefaultTotalAmount = prescriptionitemDescTotalAmount.Default.(float64)
	// prescriptionitemDescRemainAmount is the schema descriptor for remain_amount field.
	prescriptionitemDescRemainAmount := prescriptionitemFields[10].Descriptor()
	// prescriptionitem.DefaultRemainAmount holds the default value on creation for the remain_amount field.
	prescriptionitem.DefaultRemainAmount = prescriptionitemDescRemainAmount.Default.(float64)
	// prescriptionitemDescTakeAmount is the schema descriptor for take_amount field.
	prescriptionitemDescTakeAmount := prescriptionitemFields[11].Descriptor()
	// prescriptionitem.DefaultTakeAmount holds the default value on creation for the take_amount field.
	prescriptionitem.DefaultTakeAmount = prescriptionitemDescTakeAmount.Default.(float64)
	// prescriptionitemDescMedicineUnit is the schema descriptor for medicine_unit field.
	prescriptionitemDescMedicineUnit := prescriptionitemFields[12].Descriptor()
	// prescriptionitem.DefaultMedicineUnit holds the default value on creation for the medicine_unit field.
	prescriptionitem.DefaultMedicineUnit = prescriptionitemDescMedicineUnit.Default.(string)
	// prescriptionitemDescCreatedAt is the schema descriptor for created_at field.
	prescriptionitemDescCreatedAt := prescriptionitemFields[14].Descriptor()
	// prescriptionitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	prescriptionitem.DefaultCreatedAt = prescriptionitemDescCreatedAt.Default.(func() time.Time)
	// prescriptionitemDescID is the schema descriptor for id field.
	prescriptionitemDescID := prescriptionitemFields[0].Descriptor()
	// prescriptionitem.DefaultID holds the default value on creation for the id field.
	prescriptionitem.DefaultID = prescriptionitemDescID.Default.(func() uuid.UUID)
	takehistoryitemFields := schema.TakeHistoryItem{}.Fields()
	_ = takehistoryitemFields
	// takehistoryitemDescTakeStatus is the schema descriptor for take_status field.
	takehistoryitemDescTakeStatus := takehistoryitemFields[11].Descriptor()
	// takehistoryitem.DefaultTakeStatus holds the default value on creation for the take_status field.
	takehistoryitem.DefaultTakeStatus = takehistoryitemDescTakeStatus.Default.(bool)
	// takehistoryitemDescTotalAmount is the schema descriptor for total_amount field.
	takehistoryitemDescTotalAmount := takehistoryitemFields[12].Descriptor()
	// takehistoryitem.DefaultTotalAmount holds the default value on creation for the total_amount field.
	takehistoryitem.DefaultTotalAmount = takehistoryitemDescTotalAmount.Default.(float64)
	// takehistoryitemDescRemainAmount is the schema descriptor for remain_amount field.
	takehistoryitemDescRemainAmount := takehistoryitemFields[13].Descriptor()
	// takehistoryitem.DefaultRemainAmount holds the default value on creation for the remain_amount field.
	takehistoryitem.DefaultRemainAmount = takehistoryitemDescRemainAmount.Default.(float64)
	// takehistoryitemDescTakeAmount is the schema descriptor for take_amount field.
	takehistoryitemDescTakeAmount := takehistoryitemFields[14].Descriptor()
	// takehistoryitem.DefaultTakeAmount holds the default value on creation for the take_amount field.
	takehistoryitem.DefaultTakeAmount = takehistoryitemDescTakeAmount.Default.(float64)
	// takehistoryitemDescCreatedAt is the schema descriptor for created_at field.
	takehistoryitemDescCreatedAt := takehistoryitemFields[18].Descriptor()
	// takehistoryitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	takehistoryitem.DefaultCreatedAt = takehistoryitemDescCreatedAt.Default.(func() time.Time)
	// takehistoryitemDescID is the schema descriptor for id field.
	takehistoryitemDescID := takehistoryitemFields[0].Descriptor()
	// takehistoryitem.DefaultID holds the default value on creation for the id field.
	takehistoryitem.DefaultID = takehistoryitemDescID.Default.(func() uuid.UUID)
	takehistorymemoFields := schema.TakeHistoryMemo{}.Fields()
	_ = takehistorymemoFields
	// takehistorymemoDescCreatedAt is the schema descriptor for created_at field.
	takehistorymemoDescCreatedAt := takehistorymemoFields[5].Descriptor()
	// takehistorymemo.DefaultCreatedAt holds the default value on creation for the created_at field.
	takehistorymemo.DefaultCreatedAt = takehistorymemoDescCreatedAt.Default.(func() time.Time)
	// takehistorymemoDescID is the schema descriptor for id field.
	takehistorymemoDescID := takehistorymemoFields[0].Descriptor()
	// takehistorymemo.DefaultID holds the default value on creation for the id field.
	takehistorymemo.DefaultID = takehistorymemoDescID.Default.(func() uuid.UUID)
	timezoneFields := schema.TimeZone{}.Fields()
	_ = timezoneFields
	// timezoneDescIsDefault is the schema descriptor for is_default field.
	timezoneDescIsDefault := timezoneFields[3].Descriptor()
	// timezone.DefaultIsDefault holds the default value on creation for the is_default field.
	timezone.DefaultIsDefault = timezoneDescIsDefault.Default.(bool)
	// timezoneDescCreatedAt is the schema descriptor for created_at field.
	timezoneDescCreatedAt := timezoneFields[7].Descriptor()
	// timezone.DefaultCreatedAt holds the default value on creation for the created_at field.
	timezone.DefaultCreatedAt = timezoneDescCreatedAt.Default.(func() time.Time)
	// timezoneDescID is the schema descriptor for id field.
	timezoneDescID := timezoneFields[0].Descriptor()
	// timezone.DefaultID holds the default value on creation for the id field.
	timezone.DefaultID = timezoneDescID.Default.(func() uuid.UUID)
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreatedAt is the schema descriptor for created_at field.
	tokenDescCreatedAt := tokenFields[5].Descriptor()
	// token.DefaultCreatedAt holds the default value on creation for the created_at field.
	token.DefaultCreatedAt = tokenDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserStatus is the schema descriptor for user_status field.
	userDescUserStatus := userFields[4].Descriptor()
	// user.DefaultUserStatus holds the default value on creation for the user_status field.
	user.DefaultUserStatus = userDescUserStatus.Default.(string)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[5].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(string)
	// userDescFailCount is the schema descriptor for fail_count field.
	userDescFailCount := userFields[6].Descriptor()
	// user.DefaultFailCount holds the default value on creation for the fail_count field.
	user.DefaultFailCount = userDescFailCount.Default.(int)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
