// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nursing_api/pkg/ent/predicate"
	"nursing_api/pkg/ent/takehistory"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TakeHistoryUpdate is the builder for updating TakeHistory entities.
type TakeHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *TakeHistoryMutation
}

// Where appends a list predicates to the TakeHistoryUpdate builder.
func (thu *TakeHistoryUpdate) Where(ps ...predicate.TakeHistory) *TakeHistoryUpdate {
	thu.mutation.Where(ps...)
	return thu
}

// SetUserID sets the "user_id" field.
func (thu *TakeHistoryUpdate) SetUserID(u uuid.UUID) *TakeHistoryUpdate {
	thu.mutation.SetUserID(u)
	return thu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableUserID(u *uuid.UUID) *TakeHistoryUpdate {
	if u != nil {
		thu.SetUserID(*u)
	}
	return thu
}

// SetTimezoneID sets the "timezone_id" field.
func (thu *TakeHistoryUpdate) SetTimezoneID(u uuid.UUID) *TakeHistoryUpdate {
	thu.mutation.SetTimezoneID(u)
	return thu
}

// SetNillableTimezoneID sets the "timezone_id" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableTimezoneID(u *uuid.UUID) *TakeHistoryUpdate {
	if u != nil {
		thu.SetTimezoneID(*u)
	}
	return thu
}

// SetTakeDate sets the "take_date" field.
func (thu *TakeHistoryUpdate) SetTakeDate(t time.Time) *TakeHistoryUpdate {
	thu.mutation.SetTakeDate(t)
	return thu
}

// SetNillableTakeDate sets the "take_date" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableTakeDate(t *time.Time) *TakeHistoryUpdate {
	if t != nil {
		thu.SetTakeDate(*t)
	}
	return thu
}

// SetTakeStatus sets the "take_status" field.
func (thu *TakeHistoryUpdate) SetTakeStatus(s string) *TakeHistoryUpdate {
	thu.mutation.SetTakeStatus(s)
	return thu
}

// SetNillableTakeStatus sets the "take_status" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableTakeStatus(s *string) *TakeHistoryUpdate {
	if s != nil {
		thu.SetTakeStatus(*s)
	}
	return thu
}

// ClearTakeStatus clears the value of the "take_status" field.
func (thu *TakeHistoryUpdate) ClearTakeStatus() *TakeHistoryUpdate {
	thu.mutation.ClearTakeStatus()
	return thu
}

// SetMemo sets the "memo" field.
func (thu *TakeHistoryUpdate) SetMemo(s string) *TakeHistoryUpdate {
	thu.mutation.SetMemo(s)
	return thu
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableMemo(s *string) *TakeHistoryUpdate {
	if s != nil {
		thu.SetMemo(*s)
	}
	return thu
}

// ClearMemo clears the value of the "memo" field.
func (thu *TakeHistoryUpdate) ClearMemo() *TakeHistoryUpdate {
	thu.mutation.ClearMemo()
	return thu
}

// SetCreatedAt sets the "created_at" field.
func (thu *TakeHistoryUpdate) SetCreatedAt(t time.Time) *TakeHistoryUpdate {
	thu.mutation.SetCreatedAt(t)
	return thu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableCreatedAt(t *time.Time) *TakeHistoryUpdate {
	if t != nil {
		thu.SetCreatedAt(*t)
	}
	return thu
}

// SetUpdatedAt sets the "updated_at" field.
func (thu *TakeHistoryUpdate) SetUpdatedAt(t time.Time) *TakeHistoryUpdate {
	thu.mutation.SetUpdatedAt(t)
	return thu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (thu *TakeHistoryUpdate) SetNillableUpdatedAt(t *time.Time) *TakeHistoryUpdate {
	if t != nil {
		thu.SetUpdatedAt(*t)
	}
	return thu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (thu *TakeHistoryUpdate) ClearUpdatedAt() *TakeHistoryUpdate {
	thu.mutation.ClearUpdatedAt()
	return thu
}

// Mutation returns the TakeHistoryMutation object of the builder.
func (thu *TakeHistoryUpdate) Mutation() *TakeHistoryMutation {
	return thu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (thu *TakeHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, thu.sqlSave, thu.mutation, thu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (thu *TakeHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := thu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (thu *TakeHistoryUpdate) Exec(ctx context.Context) error {
	_, err := thu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thu *TakeHistoryUpdate) ExecX(ctx context.Context) {
	if err := thu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (thu *TakeHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(takehistory.Table, takehistory.Columns, sqlgraph.NewFieldSpec(takehistory.FieldID, field.TypeUUID))
	if ps := thu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := thu.mutation.UserID(); ok {
		_spec.SetField(takehistory.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := thu.mutation.TimezoneID(); ok {
		_spec.SetField(takehistory.FieldTimezoneID, field.TypeUUID, value)
	}
	if value, ok := thu.mutation.TakeDate(); ok {
		_spec.SetField(takehistory.FieldTakeDate, field.TypeTime, value)
	}
	if value, ok := thu.mutation.TakeStatus(); ok {
		_spec.SetField(takehistory.FieldTakeStatus, field.TypeString, value)
	}
	if thu.mutation.TakeStatusCleared() {
		_spec.ClearField(takehistory.FieldTakeStatus, field.TypeString)
	}
	if value, ok := thu.mutation.Memo(); ok {
		_spec.SetField(takehistory.FieldMemo, field.TypeString, value)
	}
	if thu.mutation.MemoCleared() {
		_spec.ClearField(takehistory.FieldMemo, field.TypeString)
	}
	if value, ok := thu.mutation.CreatedAt(); ok {
		_spec.SetField(takehistory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := thu.mutation.UpdatedAt(); ok {
		_spec.SetField(takehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if thu.mutation.UpdatedAtCleared() {
		_spec.ClearField(takehistory.FieldUpdatedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, thu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{takehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	thu.mutation.done = true
	return n, nil
}

// TakeHistoryUpdateOne is the builder for updating a single TakeHistory entity.
type TakeHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TakeHistoryMutation
}

// SetUserID sets the "user_id" field.
func (thuo *TakeHistoryUpdateOne) SetUserID(u uuid.UUID) *TakeHistoryUpdateOne {
	thuo.mutation.SetUserID(u)
	return thuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableUserID(u *uuid.UUID) *TakeHistoryUpdateOne {
	if u != nil {
		thuo.SetUserID(*u)
	}
	return thuo
}

// SetTimezoneID sets the "timezone_id" field.
func (thuo *TakeHistoryUpdateOne) SetTimezoneID(u uuid.UUID) *TakeHistoryUpdateOne {
	thuo.mutation.SetTimezoneID(u)
	return thuo
}

// SetNillableTimezoneID sets the "timezone_id" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableTimezoneID(u *uuid.UUID) *TakeHistoryUpdateOne {
	if u != nil {
		thuo.SetTimezoneID(*u)
	}
	return thuo
}

// SetTakeDate sets the "take_date" field.
func (thuo *TakeHistoryUpdateOne) SetTakeDate(t time.Time) *TakeHistoryUpdateOne {
	thuo.mutation.SetTakeDate(t)
	return thuo
}

// SetNillableTakeDate sets the "take_date" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableTakeDate(t *time.Time) *TakeHistoryUpdateOne {
	if t != nil {
		thuo.SetTakeDate(*t)
	}
	return thuo
}

// SetTakeStatus sets the "take_status" field.
func (thuo *TakeHistoryUpdateOne) SetTakeStatus(s string) *TakeHistoryUpdateOne {
	thuo.mutation.SetTakeStatus(s)
	return thuo
}

// SetNillableTakeStatus sets the "take_status" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableTakeStatus(s *string) *TakeHistoryUpdateOne {
	if s != nil {
		thuo.SetTakeStatus(*s)
	}
	return thuo
}

// ClearTakeStatus clears the value of the "take_status" field.
func (thuo *TakeHistoryUpdateOne) ClearTakeStatus() *TakeHistoryUpdateOne {
	thuo.mutation.ClearTakeStatus()
	return thuo
}

// SetMemo sets the "memo" field.
func (thuo *TakeHistoryUpdateOne) SetMemo(s string) *TakeHistoryUpdateOne {
	thuo.mutation.SetMemo(s)
	return thuo
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableMemo(s *string) *TakeHistoryUpdateOne {
	if s != nil {
		thuo.SetMemo(*s)
	}
	return thuo
}

// ClearMemo clears the value of the "memo" field.
func (thuo *TakeHistoryUpdateOne) ClearMemo() *TakeHistoryUpdateOne {
	thuo.mutation.ClearMemo()
	return thuo
}

// SetCreatedAt sets the "created_at" field.
func (thuo *TakeHistoryUpdateOne) SetCreatedAt(t time.Time) *TakeHistoryUpdateOne {
	thuo.mutation.SetCreatedAt(t)
	return thuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableCreatedAt(t *time.Time) *TakeHistoryUpdateOne {
	if t != nil {
		thuo.SetCreatedAt(*t)
	}
	return thuo
}

// SetUpdatedAt sets the "updated_at" field.
func (thuo *TakeHistoryUpdateOne) SetUpdatedAt(t time.Time) *TakeHistoryUpdateOne {
	thuo.mutation.SetUpdatedAt(t)
	return thuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (thuo *TakeHistoryUpdateOne) SetNillableUpdatedAt(t *time.Time) *TakeHistoryUpdateOne {
	if t != nil {
		thuo.SetUpdatedAt(*t)
	}
	return thuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (thuo *TakeHistoryUpdateOne) ClearUpdatedAt() *TakeHistoryUpdateOne {
	thuo.mutation.ClearUpdatedAt()
	return thuo
}

// Mutation returns the TakeHistoryMutation object of the builder.
func (thuo *TakeHistoryUpdateOne) Mutation() *TakeHistoryMutation {
	return thuo.mutation
}

// Where appends a list predicates to the TakeHistoryUpdate builder.
func (thuo *TakeHistoryUpdateOne) Where(ps ...predicate.TakeHistory) *TakeHistoryUpdateOne {
	thuo.mutation.Where(ps...)
	return thuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (thuo *TakeHistoryUpdateOne) Select(field string, fields ...string) *TakeHistoryUpdateOne {
	thuo.fields = append([]string{field}, fields...)
	return thuo
}

// Save executes the query and returns the updated TakeHistory entity.
func (thuo *TakeHistoryUpdateOne) Save(ctx context.Context) (*TakeHistory, error) {
	return withHooks(ctx, thuo.sqlSave, thuo.mutation, thuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (thuo *TakeHistoryUpdateOne) SaveX(ctx context.Context) *TakeHistory {
	node, err := thuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (thuo *TakeHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := thuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thuo *TakeHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := thuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (thuo *TakeHistoryUpdateOne) sqlSave(ctx context.Context) (_node *TakeHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(takehistory.Table, takehistory.Columns, sqlgraph.NewFieldSpec(takehistory.FieldID, field.TypeUUID))
	id, ok := thuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TakeHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := thuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, takehistory.FieldID)
		for _, f := range fields {
			if !takehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != takehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := thuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := thuo.mutation.UserID(); ok {
		_spec.SetField(takehistory.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := thuo.mutation.TimezoneID(); ok {
		_spec.SetField(takehistory.FieldTimezoneID, field.TypeUUID, value)
	}
	if value, ok := thuo.mutation.TakeDate(); ok {
		_spec.SetField(takehistory.FieldTakeDate, field.TypeTime, value)
	}
	if value, ok := thuo.mutation.TakeStatus(); ok {
		_spec.SetField(takehistory.FieldTakeStatus, field.TypeString, value)
	}
	if thuo.mutation.TakeStatusCleared() {
		_spec.ClearField(takehistory.FieldTakeStatus, field.TypeString)
	}
	if value, ok := thuo.mutation.Memo(); ok {
		_spec.SetField(takehistory.FieldMemo, field.TypeString, value)
	}
	if thuo.mutation.MemoCleared() {
		_spec.ClearField(takehistory.FieldMemo, field.TypeString)
	}
	if value, ok := thuo.mutation.CreatedAt(); ok {
		_spec.SetField(takehistory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := thuo.mutation.UpdatedAt(); ok {
		_spec.SetField(takehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if thuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(takehistory.FieldUpdatedAt, field.TypeTime)
	}
	_node = &TakeHistory{config: thuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, thuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{takehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	thuo.mutation.done = true
	return _node, nil
}
