// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nursing_api/pkg/ent/predicate"
	"nursing_api/pkg/ent/takehistorymemo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TakeHistoryMemoDelete is the builder for deleting a TakeHistoryMemo entity.
type TakeHistoryMemoDelete struct {
	config
	hooks    []Hook
	mutation *TakeHistoryMemoMutation
}

// Where appends a list predicates to the TakeHistoryMemoDelete builder.
func (thmd *TakeHistoryMemoDelete) Where(ps ...predicate.TakeHistoryMemo) *TakeHistoryMemoDelete {
	thmd.mutation.Where(ps...)
	return thmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (thmd *TakeHistoryMemoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, thmd.sqlExec, thmd.mutation, thmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (thmd *TakeHistoryMemoDelete) ExecX(ctx context.Context) int {
	n, err := thmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (thmd *TakeHistoryMemoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(takehistorymemo.Table, sqlgraph.NewFieldSpec(takehistorymemo.FieldID, field.TypeUUID))
	if ps := thmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, thmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	thmd.mutation.done = true
	return affected, err
}

// TakeHistoryMemoDeleteOne is the builder for deleting a single TakeHistoryMemo entity.
type TakeHistoryMemoDeleteOne struct {
	thmd *TakeHistoryMemoDelete
}

// Where appends a list predicates to the TakeHistoryMemoDelete builder.
func (thmdo *TakeHistoryMemoDeleteOne) Where(ps ...predicate.TakeHistoryMemo) *TakeHistoryMemoDeleteOne {
	thmdo.thmd.mutation.Where(ps...)
	return thmdo
}

// Exec executes the deletion query.
func (thmdo *TakeHistoryMemoDeleteOne) Exec(ctx context.Context) error {
	n, err := thmdo.thmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{takehistorymemo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (thmdo *TakeHistoryMemoDeleteOne) ExecX(ctx context.Context) {
	if err := thmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
