// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"nursing_api/pkg/ent/takehistoryitem"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TakeHistoryItemCreate is the builder for creating a TakeHistoryItem entity.
type TakeHistoryItemCreate struct {
	config
	mutation *TakeHistoryItemMutation
	hooks    []Hook
}

// Mutation returns the TakeHistoryItemMutation object of the builder.
func (thic *TakeHistoryItemCreate) Mutation() *TakeHistoryItemMutation {
	return thic.mutation
}

// Save creates the TakeHistoryItem in the database.
func (thic *TakeHistoryItemCreate) Save(ctx context.Context) (*TakeHistoryItem, error) {
	return withHooks(ctx, thic.sqlSave, thic.mutation, thic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (thic *TakeHistoryItemCreate) SaveX(ctx context.Context) *TakeHistoryItem {
	v, err := thic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thic *TakeHistoryItemCreate) Exec(ctx context.Context) error {
	_, err := thic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thic *TakeHistoryItemCreate) ExecX(ctx context.Context) {
	if err := thic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thic *TakeHistoryItemCreate) check() error {
	return nil
}

func (thic *TakeHistoryItemCreate) sqlSave(ctx context.Context) (*TakeHistoryItem, error) {
	if err := thic.check(); err != nil {
		return nil, err
	}
	_node, _spec := thic.createSpec()
	if err := sqlgraph.CreateNode(ctx, thic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	thic.mutation.id = &_node.ID
	thic.mutation.done = true
	return _node, nil
}

func (thic *TakeHistoryItemCreate) createSpec() (*TakeHistoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &TakeHistoryItem{config: thic.config}
		_spec = sqlgraph.NewCreateSpec(takehistoryitem.Table, sqlgraph.NewFieldSpec(takehistoryitem.FieldID, field.TypeInt))
	)
	return _node, _spec
}

// TakeHistoryItemCreateBulk is the builder for creating many TakeHistoryItem entities in bulk.
type TakeHistoryItemCreateBulk struct {
	config
	err      error
	builders []*TakeHistoryItemCreate
}

// Save creates the TakeHistoryItem entities in the database.
func (thicb *TakeHistoryItemCreateBulk) Save(ctx context.Context) ([]*TakeHistoryItem, error) {
	if thicb.err != nil {
		return nil, thicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(thicb.builders))
	nodes := make([]*TakeHistoryItem, len(thicb.builders))
	mutators := make([]Mutator, len(thicb.builders))
	for i := range thicb.builders {
		func(i int, root context.Context) {
			builder := thicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TakeHistoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, thicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, thicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, thicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (thicb *TakeHistoryItemCreateBulk) SaveX(ctx context.Context) []*TakeHistoryItem {
	v, err := thicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thicb *TakeHistoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := thicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thicb *TakeHistoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := thicb.Exec(ctx); err != nil {
		panic(err)
	}
}
