// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nursing_api/pkg/ent/takehistory"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TakeHistoryCreate is the builder for creating a TakeHistory entity.
type TakeHistoryCreate struct {
	config
	mutation *TakeHistoryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (thc *TakeHistoryCreate) SetUserID(u uuid.UUID) *TakeHistoryCreate {
	thc.mutation.SetUserID(u)
	return thc
}

// SetTimezoneID sets the "timezone_id" field.
func (thc *TakeHistoryCreate) SetTimezoneID(u uuid.UUID) *TakeHistoryCreate {
	thc.mutation.SetTimezoneID(u)
	return thc
}

// SetTakeDate sets the "take_date" field.
func (thc *TakeHistoryCreate) SetTakeDate(t time.Time) *TakeHistoryCreate {
	thc.mutation.SetTakeDate(t)
	return thc
}

// SetTakeStatus sets the "take_status" field.
func (thc *TakeHistoryCreate) SetTakeStatus(s string) *TakeHistoryCreate {
	thc.mutation.SetTakeStatus(s)
	return thc
}

// SetNillableTakeStatus sets the "take_status" field if the given value is not nil.
func (thc *TakeHistoryCreate) SetNillableTakeStatus(s *string) *TakeHistoryCreate {
	if s != nil {
		thc.SetTakeStatus(*s)
	}
	return thc
}

// SetMemo sets the "memo" field.
func (thc *TakeHistoryCreate) SetMemo(s string) *TakeHistoryCreate {
	thc.mutation.SetMemo(s)
	return thc
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (thc *TakeHistoryCreate) SetNillableMemo(s *string) *TakeHistoryCreate {
	if s != nil {
		thc.SetMemo(*s)
	}
	return thc
}

// SetCreatedAt sets the "created_at" field.
func (thc *TakeHistoryCreate) SetCreatedAt(t time.Time) *TakeHistoryCreate {
	thc.mutation.SetCreatedAt(t)
	return thc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (thc *TakeHistoryCreate) SetNillableCreatedAt(t *time.Time) *TakeHistoryCreate {
	if t != nil {
		thc.SetCreatedAt(*t)
	}
	return thc
}

// SetUpdatedAt sets the "updated_at" field.
func (thc *TakeHistoryCreate) SetUpdatedAt(t time.Time) *TakeHistoryCreate {
	thc.mutation.SetUpdatedAt(t)
	return thc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (thc *TakeHistoryCreate) SetNillableUpdatedAt(t *time.Time) *TakeHistoryCreate {
	if t != nil {
		thc.SetUpdatedAt(*t)
	}
	return thc
}

// SetID sets the "id" field.
func (thc *TakeHistoryCreate) SetID(u uuid.UUID) *TakeHistoryCreate {
	thc.mutation.SetID(u)
	return thc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (thc *TakeHistoryCreate) SetNillableID(u *uuid.UUID) *TakeHistoryCreate {
	if u != nil {
		thc.SetID(*u)
	}
	return thc
}

// Mutation returns the TakeHistoryMutation object of the builder.
func (thc *TakeHistoryCreate) Mutation() *TakeHistoryMutation {
	return thc.mutation
}

// Save creates the TakeHistory in the database.
func (thc *TakeHistoryCreate) Save(ctx context.Context) (*TakeHistory, error) {
	thc.defaults()
	return withHooks(ctx, thc.sqlSave, thc.mutation, thc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (thc *TakeHistoryCreate) SaveX(ctx context.Context) *TakeHistory {
	v, err := thc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thc *TakeHistoryCreate) Exec(ctx context.Context) error {
	_, err := thc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thc *TakeHistoryCreate) ExecX(ctx context.Context) {
	if err := thc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (thc *TakeHistoryCreate) defaults() {
	if _, ok := thc.mutation.TakeStatus(); !ok {
		v := takehistory.DefaultTakeStatus
		thc.mutation.SetTakeStatus(v)
	}
	if _, ok := thc.mutation.CreatedAt(); !ok {
		v := takehistory.DefaultCreatedAt()
		thc.mutation.SetCreatedAt(v)
	}
	if _, ok := thc.mutation.ID(); !ok {
		v := takehistory.DefaultID()
		thc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thc *TakeHistoryCreate) check() error {
	if _, ok := thc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TakeHistory.user_id"`)}
	}
	if _, ok := thc.mutation.TimezoneID(); !ok {
		return &ValidationError{Name: "timezone_id", err: errors.New(`ent: missing required field "TakeHistory.timezone_id"`)}
	}
	if _, ok := thc.mutation.TakeDate(); !ok {
		return &ValidationError{Name: "take_date", err: errors.New(`ent: missing required field "TakeHistory.take_date"`)}
	}
	if _, ok := thc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TakeHistory.created_at"`)}
	}
	return nil
}

func (thc *TakeHistoryCreate) sqlSave(ctx context.Context) (*TakeHistory, error) {
	if err := thc.check(); err != nil {
		return nil, err
	}
	_node, _spec := thc.createSpec()
	if err := sqlgraph.CreateNode(ctx, thc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	thc.mutation.id = &_node.ID
	thc.mutation.done = true
	return _node, nil
}

func (thc *TakeHistoryCreate) createSpec() (*TakeHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TakeHistory{config: thc.config}
		_spec = sqlgraph.NewCreateSpec(takehistory.Table, sqlgraph.NewFieldSpec(takehistory.FieldID, field.TypeUUID))
	)
	if id, ok := thc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := thc.mutation.UserID(); ok {
		_spec.SetField(takehistory.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := thc.mutation.TimezoneID(); ok {
		_spec.SetField(takehistory.FieldTimezoneID, field.TypeUUID, value)
		_node.TimezoneID = value
	}
	if value, ok := thc.mutation.TakeDate(); ok {
		_spec.SetField(takehistory.FieldTakeDate, field.TypeTime, value)
		_node.TakeDate = value
	}
	if value, ok := thc.mutation.TakeStatus(); ok {
		_spec.SetField(takehistory.FieldTakeStatus, field.TypeString, value)
		_node.TakeStatus = value
	}
	if value, ok := thc.mutation.Memo(); ok {
		_spec.SetField(takehistory.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if value, ok := thc.mutation.CreatedAt(); ok {
		_spec.SetField(takehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := thc.mutation.UpdatedAt(); ok {
		_spec.SetField(takehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TakeHistoryCreateBulk is the builder for creating many TakeHistory entities in bulk.
type TakeHistoryCreateBulk struct {
	config
	err      error
	builders []*TakeHistoryCreate
}

// Save creates the TakeHistory entities in the database.
func (thcb *TakeHistoryCreateBulk) Save(ctx context.Context) ([]*TakeHistory, error) {
	if thcb.err != nil {
		return nil, thcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(thcb.builders))
	nodes := make([]*TakeHistory, len(thcb.builders))
	mutators := make([]Mutator, len(thcb.builders))
	for i := range thcb.builders {
		func(i int, root context.Context) {
			builder := thcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TakeHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, thcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, thcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, thcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (thcb *TakeHistoryCreateBulk) SaveX(ctx context.Context) []*TakeHistory {
	v, err := thcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thcb *TakeHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := thcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thcb *TakeHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := thcb.Exec(ctx); err != nil {
		panic(err)
	}
}
