// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nursing_api/pkg/ent/predicate"
	"nursing_api/pkg/ent/takehistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TakeHistoryDelete is the builder for deleting a TakeHistory entity.
type TakeHistoryDelete struct {
	config
	hooks    []Hook
	mutation *TakeHistoryMutation
}

// Where appends a list predicates to the TakeHistoryDelete builder.
func (thd *TakeHistoryDelete) Where(ps ...predicate.TakeHistory) *TakeHistoryDelete {
	thd.mutation.Where(ps...)
	return thd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (thd *TakeHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, thd.sqlExec, thd.mutation, thd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (thd *TakeHistoryDelete) ExecX(ctx context.Context) int {
	n, err := thd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (thd *TakeHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(takehistory.Table, sqlgraph.NewFieldSpec(takehistory.FieldID, field.TypeInt))
	if ps := thd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, thd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	thd.mutation.done = true
	return affected, err
}

// TakeHistoryDeleteOne is the builder for deleting a single TakeHistory entity.
type TakeHistoryDeleteOne struct {
	thd *TakeHistoryDelete
}

// Where appends a list predicates to the TakeHistoryDelete builder.
func (thdo *TakeHistoryDeleteOne) Where(ps ...predicate.TakeHistory) *TakeHistoryDeleteOne {
	thdo.thd.mutation.Where(ps...)
	return thdo
}

// Exec executes the deletion query.
func (thdo *TakeHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := thdo.thd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{takehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (thdo *TakeHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := thdo.Exec(ctx); err != nil {
		panic(err)
	}
}
