# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ] 
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout release
      uses: actions/checkout@v3

    # Runs a single command using the runners shell 
    - name: Clean temp directory
      run: |
        rm -rf *
        echo "GITHUB_WORKSPACE : "$GITHUB_WORKSPACE
        cp -r $GITHUB_WORKSPACE . 
      
    - name: archive healthlink 
      run: tar cvfz ./healthlink.tar.gz *
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./healthlink.tar.gz s3://healthlink-api-dev/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name healthlink-dev-deploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name github-actions-deploy-group
        --s3-location bucket=healthlink-api-dev,bundleType=tgz,key=archive/healthlink.tar.gz
